version: '3'

volumes:
  mothership_scans_local_postgres_data: {}
  mothership_scans_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: mothership_scans_local_django
    container_name: mothership_scans_local_django
    platform: linux/x86_64
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: mothership_scans_production_postgres
    container_name: mothership_scans_local_postgres
    volumes:
      - mothership_scans_local_postgres_data:/var/lib/postgresql/data:Z
      - mothership_scans_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
