# Generated by Django 3.2.12 on 2022-06-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='location',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
