# Generated by Django 3.2.12 on 2022-12-15 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0003_scan_tracking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scan',
            options={'ordering': ['-time_scan']},
        ),
    ]
