# Generated by Django 3.2.12 on 2022-12-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0004_alter_scan_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='bin_success',
            field=models.BooleanField(default=False),
        ),
    ]
