# Generated by Django 3.2.12 on 2023-01-05 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0005_scan_bin_success'),
    ]

    operations = [
        migrations.CreateModel(
            name='Success',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='Success', max_length=100, null=True)),
                ('detail', models.CharField(blank=True, max_length=500, null=True)),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scans.scan')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Fail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='Fail', max_length=100, null=True)),
                ('detail', models.CharField(blank=True, max_length=500, null=True)),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scans.scan')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
