# Generated by Django 3.2.12 on 2023-01-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0006_fail_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='fail',
            name='batch_id',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='batch_id',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='success',
            name='batch_id',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
