# Generated by Django 3.2.12 on 2023-01-18 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0008_alter_fail_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fail',
            name='scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scans.scan'),
        ),
        migrations.AlterField(
            model_name='success',
            name='scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scans.scan'),
        ),
    ]
